### ISSUE TITLE
Vehicle editing screen

### ISSUE THREAD

**Issue by lechediaz** [lechediaz/condominiums-ui#16]
To access this screen, click on the license plate number of a vehicle from the table in the vehicles tab. This screen allows to edit vehicle information from a form with the following fields:

- "Placa": vehicle plate number. Required. Max 8 characters.
- "Tipo": Indicates the type of vehicle. Required. Possible values are: "Car" and "Motorcycle".

When the "Guardar" button is clicked, it should consume the API endpoint that allows modify the vehicle. Once the operation has been performed, a notification should appear indicating that the operation was successful and return to vehicles tab.

**Comment by JhoanAlvear** [comment]
assigned to me please
