### ISSUE TITLE
UI - Create Residents details page

### ISSUE THREAD

**Issue by lechediaz** [lechediaz/condominiums-ui#4]
This page shows tabs where the first tab with label "Información" allows to edit the Resident fields except the Id. To do this you must request:

Nombre. Required field. Type text. Maximum 200 characters.
Número de Casa/Apartamento: Required field, Text type. Maximum 100 characters.

There should be a button called "Guardar" where the resident's information is saved when clicked.

Should have a second Tab called "Vehículos" where will be the vehicles assigment. This will be worked from another issue.

**Comment by lechediaz** [comment]
Issue is reopened because it does not meet the objectives:

- It does not consume API endpoints to fetch information from a resident or update it.
- It does not have an update button.

I will go to work completing the requirements.

**Comment by JhoanAlvear** [comment]
ok
